# Generated by Django 5.2.4 on 2025-10-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncard',
            name='correct_answers',
            field=models.JSONField(blank=True, help_text='List of correct answers or a single correct value depending on type', null=True),
        ),
    ]
