# Generated by Django 5.2.4 on 2025-10-09 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_questioncard_correct_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='authenticator.organization'),
        ),
    ]
