# Generated by Django 5.2.4 on 2025-10-09 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0004_alter_survey_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='authenticator.organization'),
        ),
    ]
