# Generated by Django 5.2.4 on 2025-10-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0005_bot_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='identifier',
        ),
    ]
